Vagrant.configure("2") do |config|
  config.vm.hostname = "netbsd8"
  config.vm.box = "generic/netbsd8"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "netbsd8"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    PKG_PATH="http://ftp.netbsd.org/pub/pkgsrc/packages/NetBSD/amd64/8.0/All" pkg_add curl zip mozilla-rootcerts-openssl git
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    /sbin/shutdown -p now
  SHELL
end
