Vagrant.configure("2") do |config|
  config.vm.hostname = "gentoo"
  config.vm.box = "generic/gentoo"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "gentoo"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    emerge app-arch/zip dev-vcs/git sys-libs/ncurses
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    rm /home/vagrant/.bash_logout
    shutdown -h -P now
  SHELL
end
