Vagrant.configure("2") do |config|
  config.vm.hostname = "debian10"
  config.vm.box = "bento/debian-10"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian10"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
    apt-get -y install curl unzip zip git build-essential libncurses5-dev
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    rm /home/vagrant/.bash_logout
    shutdown -h -P now
  SHELL
end
