Vagrant.configure("2") do |config|
  # Seems to break Alpine images?
  #config.vm.hostname = "alpine311"
  config.vm.box = "generic/alpine311"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "alpine311"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    apk update
    apk upgrade
    apk add zip unzip curl git build-base linux-headers ncurses-dev perl
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    shutdown -h -P now
  SHELL
end
