Vagrant.configure("2") do |config|
  config.vm.hostname = "freebsd12i386"
  config.vm.box = "bento/freebsd-12.0-i386"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "freebsd12i386"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    pkg upgrade -y
    pkg install -y curl zip git bash
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    shutdown -p now
  SHELL
end
