Vagrant.configure("2") do |config|
  config.vm.hostname = "oracle7"
  config.vm.box = "bento/oracle-7.6"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "oracle7"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    yum -y update
    /usr/bin/ol_yum_configure.sh
    yum -y update
    yum -y install curl unzip zip git gcc ncurses-devel perl-Test-Simple perl-IPC-Cmd
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    shutdown -h -P now
  SHELL
end
