Vagrant.configure("2") do |config|
  config.vm.hostname = "openbsd6"
  config.vm.box = "generic/openbsd6"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "openbsd6"
  end
  config.vm.provision "file", source: "../gitlab-runner-shim.sh", destination: "/tmp/gitlab-runner"
  config.vm.provision "shell", inline: <<-SHELL
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
    pkg_add -u
    pkg_add curl zip unzip-6.0p11 git
    mv /tmp/gitlab-runner /usr/bin/gitlab-runner
    chown 0:0 /usr/bin/gitlab-runner
    chmod 755 /usr/bin/gitlab-runner
    /sbin/shutdown -p now
  SHELL
end
